import { MarketingFooter } from "./LandingPage";

const roles = [
  { id: "everyone", label: "New to Valtide", title: "Understand what Valtide validates", items: ["What Valtide is", "How to read a result", "Evidence State meanings", "Core glossary"] },
  { id: "curators", label: "Curators and risk teams", title: "Investigate and govern", items: ["Curator workflow", "Evidence versus policy", "Freshness and stale attestations", "Historical and Demo boundaries"] },
  { id: "developers", label: "Developers and integrators", title: "Consume Valtide evidence", items: ["Read-only API paths", "ValidationRegistry", "RiskGuard", "Attestation and deployment reference"] },
  { id: "researchers", label: "Researchers", title: "Review the challenger", items: ["Valuation methodology", "Prediction intervals", "Point-in-time correctness", "Evaluation limitations"] },
] as const;

const glossary = [
  ["Reference under test", "The explicitly identified price or valuation methodology Valtide evaluates. In the current NVDAx deployment, this is the OKX X-Perp NVDA index."],
  ["Valtide fair value", "The independent challenger model’s point estimate. It is a model output, not an objectively proven true price."],
  ["Prediction interval", "The calibrated uncertainty range around the challenger estimate."],
  ["Evidence State", "Valtide’s standardized interpretation of whether the reference under test is supported, inconclusive, or challenged by available evidence."],
  ["Policy Action", "A response configured by the curator or consuming protocol. It is not generated by the quant model."],
  ["Attestation", "The authorized onchain record of a validation observation stored by the ValidationRegistry."],
  ["Freshness", "Whether an attestation remains valid under both its valid-until time and the policy owner’s maximum age."],
  ["Reason codes", "Structured backend explanations for an Evidence State, preserved by the frontend without recomputation."],
] as const;

export function DocsPage() {
  return <div className="marketing-shell docs-page">
    <header className="docs-header">
      <a className="docs-brand" href="/"><span className="valtide-logo-crop"><img src="/valtide-logo.jpg" alt="" /></span><span>Valtide</span><i>Docs</i></a>
      <nav><a href="/">Product</a><a href="#glossary">Glossary</a><a href="https://valtide-api-production.up.railway.app/docs" target="_blank" rel="noreferrer">API reference ↗</a></nav>
      <a className="docs-console" href="/?view=console">Open console ↗</a>
    </header>

    <main>
      <section className="docs-hero">
        <div>
          <p className="marketing-kicker">Valtide documentation</p>
          <h1>Understand collateral valuations when markets disagree.</h1>
          <p>Valtide independently evaluates whether a tokenized-equity collateral reference remains supported by available market evidence. Learn how evidence is produced, interpreted, and made usable by curator-defined policies on X Layer.</p>
          <div className="docs-hero__actions"><a className="primary-link" href="#start">Start with Valtide ↓</a><a className="text-link" href="#glossary">Explore the glossary →</a></div>
        </div>
        <aside><span>CORE OWNERSHIP BOUNDARY</span><p><strong>Valtide</strong> determines the Evidence State.</p><p><strong>Curators</strong> define the Policy Action.</p><p><strong>Consumers</strong> enforce the resulting action.</p><small>The browser is a read-only observer.</small></aside>
      </section>

      <section id="start" className="docs-section">
        <div className="docs-section__title"><span>01</span><div><p className="marketing-kicker">Start by role</p><h2>Follow the path that matches your responsibility.</h2></div></div>
        <div className="role-grid">{roles.map((role, index) => <article id={role.id} key={role.id}><span>0{index + 1}</span><p>{role.label}</p><h3>{role.title}</h3><ul>{role.items.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div>
      </section>

      <section id="methodology" className="docs-section docs-section--flow">
        <div className="docs-section__title"><span>02</span><div><p className="marketing-kicker">How Valtide works</p><h2>From named reference to consumer-owned enforcement.</h2></div></div>
        <div className="docs-flow">
          <article><span>01 · OBSERVE</span><h3>Collect point-in-time evidence</h3><p>The selected reference, tokenized-market signal, trusted anchor, market state, freshness, and available independent evidence remain explicit.</p></article>
          <article><span>02 · ESTIMATE</span><h3>Run the independent challenger</h3><p>P1a-C produces a fair-value estimate and calibrated interval. The reference under test is excluded from the independent challenger feature set.</p></article>
          <article><span>03 · VALIDATE</span><h3>Return an Evidence State</h3><p>The backend classifies the observation and returns reason codes. The frontend does not recompute the state.</p></article>
          <article><span>04 · RESPOND</span><h3>Evaluate curator-owned policy</h3><p>RiskGuard maps fresh evidence through the consuming application’s configured policy. The consumer owns enforcement.</p></article>
        </div>
      </section>

      <section className="docs-section">
        <div className="docs-section__title"><span>03</span><div><p className="marketing-kicker">Interpretation</p><h2>Three Evidence States. No implied policy instruction.</h2></div></div>
        <div className="evidence-doc-grid">
          <article className="supported"><span>SUPPORTED</span><p>Available independent evidence does not provide a material reason to challenge the reference under test.</p><small>This does not mean the reference is proven correct.</small></article>
          <article className="inconclusive"><span>INCONCLUSIVE</span><p>Evidence is not sufficiently strong or consistent to support or materially challenge the reference.</p><small>Abstention is intentional when evidence is weak.</small></article>
          <article className="challenged"><span>CHALLENGED</span><p>The reference under test is materially inconsistent with sufficiently strong independent evidence.</p><small>This does not mean the reference is definitely wrong.</small></article>
        </div>
      </section>

      <section id="read-result" className="docs-section docs-section--reader">
        <div className="docs-section__title"><span>04</span><div><p className="marketing-kicker">Read a validation result</p><h2>Move from context to evidence before looking at policy.</h2></div></div>
        <ol className="reader-list">
          <li><span>01</span><div><strong>Confirm the context</strong><p>Operational, Historical, and Demo are separate evidence lanes. They are never silently substituted.</p></div></li>
          <li><span>02</span><div><strong>Identify the asset and reference</strong><p>Check the selected asset, observation timestamp, market state, named reference under test, and source freshness.</p></div></li>
          <li><span>03</span><div><strong>Inspect estimate and uncertainty</strong><p>Read the fair-value center and interval together. A point estimate without uncertainty is insufficient.</p></div></li>
          <li><span>04</span><div><strong>Interpret the Evidence State</strong><p>Use the deviation, evidence quality, reason codes, and source provenance. Do not infer correctness from the state name alone.</p></div></li>
          <li><span>05</span><div><strong>Separate policy and enforcement</strong><p>Policy labels are configured mappings. Current onchain enforcement is comparable only when the operational result and attestation are synchronized.</p></div></li>
        </ol>
      </section>

      <section className="docs-section docs-section--contexts">
        <div className="docs-section__title"><span>05</span><div><p className="marketing-kicker">Evidence contexts</p><h2>Operational, Historical, and Demo mean different things.</h2></div></div>
        <div className="context-grid">
          <article><span>OPERATIONAL</span><p>Latest persisted warmed result, successful scheduler history, runtime state, and current deployed control-plane reads. Gaps remain gaps.</p></article>
          <article><span>HISTORICAL</span><p>Point-in-time research panel with verified provenance. Policy labels use today’s configured mapping and are not historical onchain decisions.</p></article>
          <article><span>DEMO</span><p>Exactly six canonical five-minute observations in the deterministic <code>weekend_divergence</code> scenario. It is not track record or historical performance.</p></article>
        </div>
      </section>

      <section id="glossary" className="docs-section">
        <div className="docs-section__title"><span>06</span><div><p className="marketing-kicker">Core glossary</p><h2>Use the product’s terms precisely.</h2></div></div>
        <dl className="glossary-grid">{glossary.map(([term, definition]) => <div key={term}><dt>{term}</dt><dd>{definition}</dd></div>)}</dl>
      </section>

      <section className="docs-section docs-section--scope">
        <div>
          <p className="marketing-kicker">Current product scope</p>
          <h2>A defensible vertical slice, not a fabricated asset universe.</h2>
          <dl><div><dt>Supported asset</dt><dd>NVDAx / NVDA</dd></div><div><dt>Roadmap asset</dt><dd>SPYx · not onboarded</dd></div><div><dt>Reference under test</dt><dd>OKX X-Perp NVDA index</dd></div><div><dt>Network</dt><dd>X Layer testnet · 1952</dd></div><div><dt>Model</dt><dd>P1a-C · 0.2.0</dd></div></dl>
        </div>
        <div>
          <p className="marketing-kicker">Trust and limitations</p>
          <h2>What the interface must never imply.</h2>
          <ul><li>No exact “true” fair value is observable while the strongest market is closed.</li><li>Cross-source agreement is not proof of truth; systems may share data or methodology.</li><li>Historical diagnostics are research evidence, not production guarantees.</li><li>The testnet contracts are not audited production lending infrastructure.</li><li>Valtide does not choose a universal LTV, trade, liquidate, or custody assets.</li></ul>
        </div>
      </section>

      <section className="docs-cta"><div><p className="marketing-kicker">Move from explanation to evidence</p><h2>Inspect the current interface or review the source.</h2></div><div><a className="primary-link" href="/?view=console">Open validation console ↗</a><a className="text-link" href="https://github.com/chin0312/valtide" target="_blank" rel="noreferrer">View repository ↗</a></div></section>
    </main>
    <MarketingFooter />
  </div>;
}
